### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by maoschanz** [Maestroschan/nautilus-create-launcher#1]
According to the specs:

- [x] launchers should be able to target files
- [x] empty fields are not supposed to exist

Also:

- [x] Tooltip for categories, because no one will guess them
- [x] not allow clicking on "next" if the name is empty
- [ ] what happens if i create 2 launchers with the same name ?

Other things to ask to the user:

- [ ] a switch concerning the terminal
- [ ] mime types ?
